# Generated by Django 4.2 on 2026-03-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_bitacora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacora',
            options={'ordering': ['-fecha'], 'verbose_name': 'Registro de Bitácora', 'verbose_name_plural': 'Registros de Bitácora'},
        ),
    ]
