# Generated by Django 4.2 on 2026-03-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_alter_bitacora_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='objeto_repr',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
