# Generated by Django 4.2 on 2026-03-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_bitacora_objeto_repr'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='cambios_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='datos_antes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='datos_despues',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='ip_usuario',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
